name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/maven-build.yml
    with:
      java-version: "17"

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-ec2.yml
    secrets: inherit