name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    uses: ./.github/workflows/build.yaml
    with:
      build_type: spring-boot

  deploy:
    needs: build
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      build_type: spring-boot
    secrets: inherit