name: Main Pipeline

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:

  build:
    uses: ./.github/workflows/build.yaml
    with:
      build_type: spring-boot

  deploy-dev:
    needs: build
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      environment: DEV
      cluster: springboot-maven-cluster
      service: workflow-definition

  deploy-prod:
    needs: deploy-dev
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      environment: PROD
      cluster: springboot-maven-cluster
      service: workflow-definition